-- public.categoria definição

-- Drop table

-- DROP TABLE public.categoria;

CREATE TABLE public.categoria (
	id int4 NOT NULL,
	descricao varchar(100) NOT NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (id)
);


-- public.schema_migrations definição

-- Drop table

-- DROP TABLE public.schema_migrations;

CREATE TABLE public.schema_migrations (
	"version" varchar(255) NOT NULL,
	applied_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);


-- public.usuario definição

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	email varchar NOT NULL,
	nome varchar NOT NULL,
	datanascimento timestamp NOT NULL,
	senha int4 NOT NULL,
	confirmarsenha int4 NOT NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);


-- public.despesa definição

-- Drop table

-- DROP TABLE public.despesa;

CREATE TABLE public.despesa (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descricao varchar(50) NULL,
	categoria_id int4 NULL,
	CONSTRAINT pk_despesa PRIMARY KEY (id),
	CONSTRAINT fk_despesa_categoria FOREIGN KEY (categoria_id) REFERENCES public.categoria(id)
);


-- public."resumoFinanceiro" definição

-- Drop table

-- DROP TABLE public."resumoFinanceiro";

CREATE TABLE public."resumoFinanceiro" (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	valordespesatotal numeric NOT NULL,
	datainclusao date DEFAULT now() NOT NULL,
	ano int4 NOT NULL,
	mes int4 NOT NULL,
	valorentradatotal numeric NOT NULL,
	"usuarioId" uuid NOT NULL,
	CONSTRAINT despesas_pkey PRIMARY KEY (id),
	CONSTRAINT usuario_id_fkey FOREIGN KEY ("usuarioId") REFERENCES public.usuario(id)
);


-- public.despesasitem definição

-- Drop table

-- DROP TABLE public.despesasitem;

CREATE TABLE public.despesasitem (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descricao varchar NOT NULL,
	valor numeric NOT NULL,
	despesaid uuid NOT NULL,
	pago bool NOT NULL,
	datainclusao date NULL,
	CONSTRAINT despesasitem_pkey PRIMARY KEY (id),
	CONSTRAINT fk_despesasitem_despesas FOREIGN KEY (despesaid) REFERENCES public."resumoFinanceiro"(id) ON DELETE CASCADE
);


-- public.entradaitem definição

-- Drop table

-- DROP TABLE public.entradaitem;

CREATE TABLE public.entradaitem (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	entradadescricao varchar NOT NULL,
	entradavalor numeric NOT NULL,
	entrada_id uuid NOT NULL,
	datapagamento date NULL,
	CONSTRAINT entradaitem_pkey PRIMARY KEY (id),
	CONSTRAINT fk_entradaitem_despesas FOREIGN KEY (entrada_id) REFERENCES public."resumoFinanceiro"(id) ON DELETE CASCADE
);


-- public.importacao_extrato definição

-- Drop table

-- DROP TABLE public.importacao_extrato;

CREATE TABLE public.importacao_extrato (
	id_resumo_financeiro uuid NOT NULL,
	usuario_id uuid NOT NULL,
	data_importacao date DEFAULT now() NOT NULL,
	status int4 NOT NULL,
	quantidade_lancamentos int4 NOT NULL,
	referencia_mes int4 NOT NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT importacao_extrato_pkey PRIMARY KEY (id),
	CONSTRAINT fk_importacao_resumo FOREIGN KEY (id_resumo_financeiro) REFERENCES public."resumoFinanceiro"(id),
	CONSTRAINT fk_importacao_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);